import { Router } from "express";
import authRoutes from "./auth.route.js";
import userRoutes from "./user.route.js";
import workspaceRoutes from "./workspace.route.js";
import workspaceMemberRoutes from "./workspaceMember.route.js";
import workspaceInviteRoutes from "./workspaceInvite.route.js";
import boardRoutes from "./board.route.js";
import columnRoutes from "./column.route.js";
import taskRoutes from "./task.route.js";
import commentRoutes from "./comment.route.js";
import attachmentRoutes from "./attachment.route.js";
import notificationRoutes from "./notification.route.js";
import channelRoutes from "./channel.route.js";
import messageRoutes from "./message.route.js";
import subscriptionRoutes from "./subscription.route.js";
import khaltiRoutes from "./khalti.route.js";
import dmRoutes from "./dm.route.js";
import contactRoutes from "./contact.route.js";
import adminRoutes from "./admin.route.js";
const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/subscriptions", subscriptionRoutes);
router.use("/khalti", khaltiRoutes);
router.use("/workspaces", workspaceRoutes);
router.use("/workspaces", workspaceMemberRoutes);
router.use("/workspaces", workspaceInviteRoutes);
router.use("/", boardRoutes);
router.use("/", columnRoutes);
router.use("/", taskRoutes);
router.use("/", commentRoutes);
router.use("/", attachmentRoutes);
router.use("/notifications", notificationRoutes);
router.use("/", channelRoutes);
router.use("/", messageRoutes);
router.use("/", dmRoutes);
router.use("/", contactRoutes);
router.use("/admin", adminRoutes);

export default router;
